apiVersion: apps/v1
kind: Deployment

metadata:
  name: app

spec:
  template:
    spec:
      containers:
        - name: app
          image: david-example-image:latest
          imagePullPolicy: IfNotPresent
