[tool.poetry]
name = "development"
version = "0.1.0"
description = ""
authors = ["David Vujic <david@vujic.se>"]
readme = "README.md"
packages = [
    {include = "development"},
    {include = "demo/my_logger", from = "components/my_logger/src"},
    {include = "demo/hello", from = "components/hello/src"},
    {include = "demo/my_script", from = "bases/my_script/src"},
]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
