[tool.polylith]
namespace = "example"
git_tag_pattern = "stable-*"

[tool.polylith.structure]
theme = "loose"

[tool.polylith.tag.patterns]
stable = "stable-*"
release = "v[0-9]-*"

[tool.polylith.test]
enabled = true
