kind: Kustomization

namePrefix: consumer-

resources:
  - ../../../../_kubernetes/services/api/development

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: service-props
    behavior: merge
    literals:
      - SOMETHING=specific-for-development
