kind: Kustomization

namePrefix: my-fastapi-project-

resources:
  - ../../../../_kubernetes/services/api/development

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: app-env
    behavior: merge
    literals:
      - SOMETHING=specific-for-development
