version: '2.1'
orbs:
  python: circleci/python@2.1.1

commands:
  install-polylith:
    steps:
      - run:
          command: |
            poetry self add poetry-multiproject-plugin
            poetry self add poetry-polylith-plugin
          name: Install the Polylith Poetry plugins
  test-bricks:
    steps:
      - run:
          command: |
            changes="$(poetry poly diff --bricks --short | tr -d '\n')"
            query="${changes//,/ or }"

            if [ -n "$query" ]; then
                poetry run pytest -k \<<< echo "$query"
            fi
          name: Run pytest on changed bricks
  lint:
    steps:
      - run:
          command: poetry run flake8
  type-check:
    steps:
      - run:
          command: poetry run mypy .

jobs:
  test:
    executor:
      name: python/default
      tag: "3.11"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - lint
      - test-bricks


workflows:
  main:
    jobs:
      - test:
          pre-steps:
            - install-polylith
