version: '2.1'
orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    executor:
      name: python/default
      tag: "3.11"
    steps:
      - checkout
      - run:
          command: |
            poetry self add poetry-multiproject-plugin
            poetry self add poetry-polylith-plugin
          name: Install Poetry plugins
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run flake8
            poetry run mypy .
          name: Linting
      - run:
          command: |
            poetry poly diff --bricks
          name: Testing

workflows:
  main:
    jobs:
      - test
