version: '2.1'
orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    executor:
      name: python/default
      tag: "3.11"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - lint
      - test-bricks
      - deploy-projects

workflows:
  main:
    jobs:
      - test:
          pre-steps:
            - install-polylith

commands:
  install-polylith:
    steps:
      - run:
          command: |
            poetry self add poetry-multiproject-plugin
            poetry self add poetry-polylith-plugin
  test-bricks:
    steps:
      - run:
          command: |
            changes="$(poetry poly diff --bricks --short | tr -d '\n')"
            query="${changes//,/ or }"

            if [ -n "$query" ]; then
                poetry run pytest -k \<<< echo "$query"
            fi
  lint:
    steps:
      - run:
          command: poetry run flake8
  type-check:
    steps:
      - run:
          command: poetry run mypy .
  deploy-projects:
    steps:
      - run:
          command: |
            diff="$(poetry poly diff --short | tr -d '\n')"
            IFS=',' projects=($diff)

            for project in "${projects[@]}"; do
              echo "The Project $project should be deployed"
            done
