version: '2.1'
orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    executor:
      name: python/default
      tag: "3.11"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run flake8
            poetry run mypy bases
            poetry run mypy components
          name: Linting
      - run:
          command: |
            changes="$(poetry poly diff --bricks --short | tr -d '\n')"
            query="${changes//,/ or }"

            poetry run pytest -k \<<< echo "$query"
          name: Testing

commands:
  install-polylith:
    description: Install the Polylith Poetry plugins
    steps:
      - run:
          command: |
            poetry self add poetry-multiproject-plugin
            poetry self add poetry-polylith-plugin
          name: Install the Polylith Poetry plugins


workflows:
  main:
    jobs:
      - test:
          pre-steps:
            - install-polylith
