kind: Kustomization

namePrefix: production-

resources:
  - ../../base

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: app-env
    behavior: merge
    literals:
      - ENV=production
